/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.gui;

import hotel.bo.UsuarioBo;
import hotel.dao.UsuarioDAO;
import hotel.entities.MiError;
import hotel.entities.Usuario;
import javax.swing.BorderFactory;
import javax.swing.border.Border;

/**
 *
 * @author pc
 */
public class FrmSignIn extends javax.swing.JFrame {

    private Border line;
    private Usuario u;
    private int funcion;
    private String cedula;
    /**
     * Creates new form FrmSignIn
     */
    public FrmSignIn() {
        initComponents();
        setLocationRelativeTo(null);
        setButtons();
        u = new Usuario();
        funcion = 1;
        line = BorderFactory.createLineBorder(java.awt.Color.BLUE, 1);
        lblBuscar.setVisible(false);
    }

    public FrmSignIn(Usuario u1, int num) {
        initComponents();
        setLocationRelativeTo(null);
        setButtons();
        u = u1;
        funcion = num;
        line = BorderFactory.createLineBorder(java.awt.Color.BLUE, 1);
        if (funcion == 2 || funcion == 3) {
            lblBuscar.setVisible(true);
        } else {
            lblBuscar.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbxPuesto = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNacionalidad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        txtContrasena = new javax.swing.JPasswordField();
        lblError = new javax.swing.JLabel();
        txtReContrasena = new javax.swing.JPasswordField();
        btnExit = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        btnAtras = new javax.swing.JButton();
        lblBuscar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Sign In");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 80, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Puesto:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        cbxPuesto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbxPuesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Recepcionista", "Mucama" }));
        cbxPuesto.setFocusable(false);
        getContentPane().add(cbxPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 190, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nombre:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        txtNombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 190, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Cedula:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        txtCedula.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 190, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Nacionalidad:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        txtNacionalidad.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtNacionalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 190, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Email:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, -1, -1));

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 190, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Teléfono:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, -1, -1));

        txtTelefono.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 190, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Nombre de Usuario:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, -1, -1));

        txtUserName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 190, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Contraseña:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Re-Contraseña:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, -1, -1));

        btnRegistrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add1.png"))); // NOI18N
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseExited(evt);
            }
        });
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 80, -1));

        txtContrasena.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 190, -1));

        lblError.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(lblError, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 394, 420, 20));

        txtReContrasena.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtReContrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 190, -1));

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 0, 40, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Apellido:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        txtApellido.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 190, -1));

        btnAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/atras.png"))); // NOI18N
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        lblBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N
        lblBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBuscarMousePressed(evt);
            }
        });
        getContentPane().add(lblBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FondoI.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0)));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        switch (funcion) {
            case 1:
                registrar();
                break;
            case 2:
                modificar();
                break;
            case 3:
                eliminar();
                break;
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseEntered
        btnRegistrar.setBorder(line);
    }//GEN-LAST:event_btnRegistrarMouseEntered

    private void btnRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseExited
        btnRegistrar.setBorder(null);
    }//GEN-LAST:event_btnRegistrarMouseExited

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        FrmPrincipal frm = new FrmPrincipal(u);
        frm.setVisible(true);
        frm.setLocationRelativeTo(null);
        dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void lblBuscarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBuscarMousePressed
        try {
            if (!txtCedula.getText().trim().equals("")) {
                UsuarioDAO udao = new UsuarioDAO();
                Usuario u = udao.cargarDatos(txtCedula.getText().trim());
                if (!(u == null)) {
                    cargarDatos(u);
                    cedula = u.getCedula();
                } else {
                    lblError.setText("El Usuario no Existe.");
                }
            }
        } catch (MiError ex) {
            lblError.setText(ex.getMessage());
        }
    }//GEN-LAST:event_lblBuscarMousePressed

    public void registrar() {
        try {
            Usuario u = new Usuario();
            u.setCedula(txtCedula.getText().trim());
            u.setEmail(txtEmail.getText().trim());
            u.setNacionalidad(txtNacionalidad.getText().trim());
            u.setNombre(txtNombre.getText().trim());
            u.setPuesto(cbxPuesto.getSelectedItem().toString());
            u.setNombreUsu(txtUserName.getText().trim());
            u.setContrasena(String.valueOf(txtContrasena.getPassword()));
            u.setTelefono(Integer.valueOf(txtTelefono.getText()));
            u.setApellido(txtApellido.getText().trim());
            UsuarioBo ubo = new UsuarioBo();

            if (ubo.verificarRegistro(u, String.valueOf(txtReContrasena.getPassword()),funcion,cedula)) {
                lblError.setText("Usuario Registrado con Éxito.");
            } else {
                lblError.setText("Intente Nuevamenta.");
            }
        } catch (NumberFormatException ex) {
            lblError.setText("Formato de telefono incorrecto.");
        } catch (MiError ex) {
            lblError.setText(ex.getMessage());
        } catch (Exception ex) {
            System.out.println("Error!!!");
        }
    }

    public void modificar() {
        try {
            Usuario u = new Usuario();
            u.setCedula(txtCedula.getText().trim());
            u.setEmail(txtEmail.getText().trim());
            u.setNacionalidad(txtNacionalidad.getText().trim());
            u.setNombre(txtNombre.getText().trim());
            u.setPuesto(cbxPuesto.getSelectedItem().toString());
            u.setNombreUsu(txtUserName.getText().trim());
            u.setContrasena(String.valueOf(txtContrasena.getPassword()));
            u.setTelefono(Integer.valueOf(txtTelefono.getText()));
            u.setApellido(txtApellido.getText().trim());
            UsuarioBo ubo = new UsuarioBo();
             if (ubo.verificarRegistro(u, String.valueOf(txtReContrasena.getPassword()),funcion,cedula))  {
                lblError.setText("Usuario Actualizado con Éxito.");
            } else {
                lblError.setText("Intente Nuevamenta.");
            }
        } catch (NumberFormatException ex) {
            lblError.setText("Formato de telefono incorrecto.");
        } catch (MiError ex) {
            lblError.setText(ex.getMessage());
        } catch (Exception ex) {
            System.out.println("Error!!!");
        }
    }

    public void eliminar() {
        try {
            UsuarioDAO udao = new UsuarioDAO();
            if (udao.eliminarUsu(txtCedula.getText().trim())) {
                lblError.setText("Usuario Eliminado.");
            } else {
                lblError.setText("Intente Nuevamente.");
            }
        } catch (MiError ex) {
            lblError.setText(ex.getMessage());
        } catch (Exception ex) {
        }
    }

    public void cargarDatos(Usuario u) {
        txtApellido.setText(u.getApellido());
        txtCedula.setText(u.getCedula());
        txtContrasena.setText(u.getContrasena());
        txtEmail.setText(u.getEmail());
        txtNacionalidad.setText(u.getNacionalidad());
        txtNombre.setText(u.getNombre());
        txtReContrasena.setText(u.getContrasena());
        txtTelefono.setText(String.valueOf(u.getTelefono()));
        txtUserName.setText(u.getNombreUsu());
        if (u.getPuesto().equals("Recepcionista")) {
            cbxPuesto.setSelectedIndex(0);
        } else {
            cbxPuesto.setSelectedIndex(1);
        }
    }

    public void setButtons() {
        btnExit.setContentAreaFilled(false);
        btnExit.setBorder(null);
        btnRegistrar.setContentAreaFilled(false);
        btnRegistrar.setBorder(null);
        btnAtras.setContentAreaFilled(false);
        btnAtras.setBorder(null);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSignIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmSignIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbxPuesto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblError;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNacionalidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtReContrasena;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
